"""Add status to BulkUpdateLog

Revision ID: 13b56853e2c0
Revises: da7f252802f5
Create Date: 2025-10-16 21:16:32.172618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b56853e2c0'
down_revision = 'da7f252802f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_update_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_update_log', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
