"""Add is_online to AllowedUser

Revision ID: 2c07571d3c0e
Revises: 0491c2380f73
Create Date: 2025-10-14 19:31:41.657203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c07571d3c0e'
down_revision = '0491c2380f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowed_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_online', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowed_users', schema=None) as batch_op:
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
